server:
  port: ${service.port:8080}
  contextPath: /challenge-microservice

#spring:
#  profiles: docker
#
#  db:
#    hibernate.auto: validate
#    datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost/postgres
#      username: postgres
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect