spring.h2.console.enabled: true

server:
  port: ${service.port:8080}
  contextPath: /challenge-microservice

spring:
  db:
    hibernate.auto: create-drop
    datasource:
      driver-class-restaurantCode: org.h2.Driver
      url: jdbc:h2:file:~/h2-database;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

ignite:
    instanceName: challenge-cache
    cassandraContactPoint: 127.0.0.1
    ipFinderRange: 127.0.0.1:47500..47509